---
abstract: 'collection of modules for rapid app development'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.024, CPAN::Meta::Converter version 2.150010'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Z
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Z:
    file: lib/Z.pm
    version: '0.004'
recommends:
  JSON::MaybeXS: '0'
  PerlX::Maybe::XS: '0'
  indirect: '0'
  perl: '5.014000'
requires:
  Import::Into: '0'
  List::Util: '1.54'
  Module::Runtime: '0'
  Object::Adhoc: '0.004'
  Path::Tiny: '0.101'
  Syntax::Keyword::Try: '0.018'
  Try::Tiny: '0.30'
  Types::Common::Numeric: '0'
  Types::Common::String: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '1.010000'
  Zydeco::Lite: '0.073'
  match::simple: '0.010'
  namespace::autoclean: '0'
  perl: '5.008008'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Z/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Z
  homepage: https://metacpan.org/release/Z
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-z.git
version: '0.004'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
